import React from 'react'
import Head from 'next/head'


interface PageProps {
  title: string,
  children?: React.ReactNode;
}

const Page: React.FC<PageProps> = (props) => {
  const { title, children } = props

  return (
    <React.Fragment>
      <Head>
        <title>
          {title}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {children}
      </main>
    </React.Fragment>
  )
}

export default Page
